kind: "AppHostingBackend"
apiVersion: "v1beta"
runConfig:
  minInstances: 0
  maxInstances: 10
  memoryMiB: 512
env:
  - variable: NEXT_PUBLIC_FIREBASE_API_KEY
    value: "AIzaSyDXp9kw39dEaBsGOELBJXU2-TGPBIVWAgM"
  - variable: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    value: "work-finder-2026.firebaseapp.com"
  - variable: NEXT_PUBLIC_FIREBASE_PROJECT_ID
    value: "work-finder-2026"
  - variable: NEXT_PUBLIC_FIREBASE_APP_ID
    value: "1:490601983473:web:120000f634606d45746850"
  - variable: GEMINI_API_KEY
    secret: GEMINI_API_KEY
